LoveBank.Web.Admin/Controllers/MachineModuleController.cs
using System.Linq;
using System;
using System.Web.Mvc;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;
using LoveBank.Common;
using LoveBank.Core.Domain;
using LoveBank.Services.AdminModule;
using LoveBank.Common.Data;
using LoveBank.Web.Admin.Models;
using LoveBank.MVC.Security;
using LoveBank.Core.MSData;
using LoveBank.Core.Domain.Enums;
using System.IO;
using System.Web;
using LoveBank.Services;
using LoveBank.Core.SerializerHelp;
using System.Collections.Generic;

namespace LoveBank.Web.Admin.Controllers
{
       [SecurityModule(Name = "一体机显示板块配置")]
    public class MachineModuleController : BaseController
    {
        /// <summary>
        /// 每页条数 
        /// </summary>
        const int PageSize = 20;


        [SecurityNode(Name = "首页")]
        public ActionResult Index(MachineModuleShowManageModel model,int? page, int? pageSize)
        {
            var pageNumber = page ?? 1;
            var size = pageSize ?? PageSize;

            using (LoveBankDBContext db = new LoveBankDBContext())
            {

                var ad = db.T_MachineModuleShowManage;
                var t_m = db.T_Machine;
                var t_d = db.T_Department;

                var list = from a in ad
                           join d in t_d on a.DeptId equals d.Id
                           select new MachineModuleShowManageModel
                           {
                               LinkUrl = a.LinkUrl,
                               ModuleKey = a.ModuleKey,
                               Name = a.Name,
                               IconUrl = a.IconUrl,
                               Sort = a.Sort,
                               Guid = a.Guid,
                               Type = a.Type,
                               AddTime = a.AddTime,
                               ID = a.ID,
                               DeptId = a.DeptId,
                               Department = d,
                               State = a.State
                           };

                list = list.Where(x => x.State != RowState.删除 && x.DeptId.IndexOf(AdminUser.DeptId) > -1);
                if (!string.IsNullOrEmpty(model.DeptId)) list = list.Where(x => x.DeptId.IndexOf(model.DeptId) > -1);


                model.MachineModuleModelList = list.OrderByDescending(x => x.ID).ToPagedList(pageNumber - 1, size);

                var list2 = t_d.Where(x => x.Level <= 6 && x.Id.IndexOf(AdminUser.DeptId) > -1).ToList();
                ViewData["Department_List"] = HelpSerializer.JSONSerialize<List<Department>>(list2);
                return View(model);
            }
        }


        [SecurityNode(Name = "添加页面")]
        public ActionResult Add()
        {

            using (LoveBankDBContext db = new LoveBankDBContext())
            {
                var dep = db.T_Department;

                //部门组织
                //var list = DbProvider.D<Department>().Where(x => x.Level <= 6).ToList();
                var list = dep.Where(x => x.Level <= 6).ToList();
                ViewData["Department_List"] = HelpSerializer.JSONSerialize<List<Department>>(list);

                return View();
            }
        }

        [HttpPost]
        [SecurityNode(Name = "添加执行")]
        public ActionResult PostAdd(MachineModuleShowManageModel parm)
        {
            #region 初始化参数
            MachineModuleShowManage model = new MachineModuleShowManage();

            model.AddTime = DateTime.Now;
            model.AddUserId = AdminUser.ID;
            model.State = RowState.有效;
            model.Guid = Guid.NewGuid().ToString();


            model.DeptId = parm.DeptId;
            model.IconUrl = parm.IconUrl;
            model.LinkUrl = parm.LinkUrl;
            model.ModuleKey = parm.ModuleKey;
            model.Name = parm.Name;
            model.Sort = parm.Sort;
            model.Type = parm.Type;
            model.Icon = parm.Icon;
            foreach (var item in parm.SourceFileList)
            {
                item.Guid = model.Guid;
                item.AddTime = DateTime.Now;

            }
            #endregion

            using (LoveBankDBContext db = new LoveBankDBContext())
            {

                db.Add(model);
                db.SaveChanges();
                db.T_SourceFile.AddRange(parm.SourceFileList);
                db.SaveChanges();

                return Success("添加成功");

            }


        }

        [SecurityNode(Name = "编辑页面")]
        public ActionResult Edit(int id)
        {
            using (LoveBankDBContext db = new LoveBankDBContext())
            {

                var ad = db.T_MachineModuleShowManage;
                var t_m = db.T_Machine;
                var t_d = db.T_Department;
                var t_s = db.T_SourceFile;

                //部门组织
                var list = db.T_Department.Where(x => x.Level <= 6).ToList();
                ViewData["Department_List"] = HelpSerializer.JSONSerialize<List<Department>>(list);

                var model = (from a in ad
                             join d in t_d on a.DeptId equals d.Id
                             where a.ID == id
                             select new MachineModuleShowManageModel
                             {
                                 LinkUrl = a.LinkUrl,
                                 ModuleKey = a.ModuleKey,
                                 Name = a.Name,
                                 IconUrl = a.IconUrl,
                                 Sort = a.Sort,
                                 Guid = a.Guid,
                                 Type = a.Type,
                                 AddTime = a.AddTime,
                                 ID = a.ID,
                                 DeptId = a.DeptId,
                                 Department = d,
                                 State = a.State,
                                 Icon=a.Icon,
                                 SourceFileList = t_s.Where(x => x.Guid == a.Guid).ToList()
                             }).FirstOrDefault();

                return View(model);
            }

        }

        [HttpPost]
        [SecurityNode(Name = "编辑执行")]
        public ActionResult PostEdit(MachineModuleShowManageModel parm)
        {



            using (LoveBankDBContext db = new LoveBankDBContext())
            {

                var t_m = db.T_Machine;
                var t_a = db.T_LoveBank_Ad;
                var t_s = db.T_SourceFile;
                var am = db.T_MachineModuleShowManage;

                #region 初始化参数
                MachineModuleShowManage model = am.Find(parm.ID);


                model.AddTime = DateTime.Now;
                model.AddUserId = AdminUser.ID;
                model.State = RowState.有效;
                //model.Guid = Guid.NewGuid().ToString();


                model.DeptId = parm.DeptId;
                model.IconUrl = parm.IconUrl;
                model.LinkUrl = parm.LinkUrl;
                model.ModuleKey = parm.ModuleKey;
                model.Name = parm.Name;
                model.Sort = parm.Sort;
                model.Type = parm.Type;
                model.Icon = parm.Icon;
               
                foreach (var item in parm.SourceFileList)
                {
                    item.Guid = model.Guid;
                    item.AddTime = DateTime.Now;

                }



                ///删除原来的,彻底以新增方式进行（修改通过删除在新增实现）
                var delSourceFile = from s in t_s where s.Guid == model.Guid select s;
                db.T_SourceFile.RemoveRange(delSourceFile);
                db.SaveChanges();
                #endregion

                db.Update<MachineModuleShowManage>(model);
                db.SaveChanges();

                foreach (var item in parm.SourceFileList)
                {
                    item.Guid = model.Guid;
                    item.AddTime = DateTime.Now;
                }

                db.T_SourceFile.AddRange(parm.SourceFileList);//重新绑定
                db.SaveChanges();

                return Success("修改成功");

            }

        }

        [HttpPost]
        [SecurityNode(Name = "删除执行")]
        public ActionResult Delete(int id)
        {
            var ad = DbProvider.D<MachineModuleShowManage>().FirstOrDefault(x => x.ID == id);
            ad.State = LoveBank.Core.Domain.Enums.RowState.删除;
            DbProvider.SaveChanges();
            return Success("删除成功");
        }

        public ActionResult UpLoadProcess(string id, string name, string type, string lastModifiedDate, int size, HttpPostedFileBase file)
        {
            if (file == null)
            {
                Error("请选择文件");
            }
            SourceFile res = UploadFileInstance.SaveFile(file, "MachineModuleShowManageImg", AdminUser.ID);
            return Json(res);
        }






    }
}

LoveBank.Web.Admin/Views/MachineModule/Add.cshtml
@using LoveBank.MVC

@Html.IncludeCSS("~/Content/plug-in/webuploader/webuploader.css")
@Html.IncludeScript("~/Content/plug-in/webuploader/webuploader.js")
@Html.IncludeCSS("~/Content/Css/demo.css")
@Html.IncludeCSS("~/Content/plug-in/webuploader/demo.css")

<div id="p" class="easyui-panel" title="新增一体机授权" data-options="tools:'#tt'">
    @using (Html.BeginForm("PostAdd", "MachineModule", FormMethod.Post, new { name = "AddForm", id = "AddForm" }))
    {
        <table class="form">


            <tr>
                <td class="item_title">
                    模块名称:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " id="Name" name="Name"
                            data-options="required:true,validType:'length[2,20]'" /> (必须填)

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    连接Url:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " name="LinkUrl" id="LinkUrl"
                           data-options="required:true,validType:'length[3,500]'" /> (必填)

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    顺序:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " name="Sort" id="Sort"
                        value="0"    data-options="required:true,validType:'length[1,5]'" /> (必填)

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    自定义唯一标识:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " name="ModuleKey" id="ModuleKey"
                           data-options="required:false,validType:'length[1,50]'" /> 
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    压下图标:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " name="Icon" id="Icon"
                           data-options="required:false,validType:'length[1,200]'" />
                </td>
            </tr>
            
            <tr>
                <td class="item_title">
                    显示Icon:
                </td>
                <td class="item_input">
                    <div id="uploader" class="wu-example uploader" style="width:700px;margin-left:0px;">
                        <div class="queueList" style=" margin:0px; ">
                            <div id="dndArea" class="placeholder">
                                <div id="filePicker"></div>
                                <p>或将文件拖到这里,多可选5个文件（只能上传视频或者图片）</p>
                            </div>
                        </div>
                        <div class="statusBar" style="display:none;">
                            <div class="progress">
                                <span class="text">0%</span>
                                <span class="percentage"></span>
                            </div><div class="info"></div>
                            <div class="btns">
                                <div id="filePicker2" class="filePicker2"></div><div class="uploadBtn">开始上传</div>
                            </div>
                        </div>
                    </div>

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    模块覆盖区域:
                </td>
                <td class="item_input">
                    <input type="hidden" name="DeptId" id="DeptId" />
                    <input type="text"  class="easyui-validatebox" data-options="prompt:'必填.',required:true" style="height:25px; width:260px;   " id="CoverCommunity" name="CoverCommunity"  />(必填)
                    <div id="menuContent" class="menuContent" style="display:none; z-index:10000;width:260px;  position: absolute;">
                        <ul id="ztree" class="ztree" style="margin-top:0; background-color:#edf3f7;  overflow:scroll; border:solid 1px #ccc;"></ul>
                    </div>

                </td>
            </tr>
     
            <tr>
                <td class="item_title"></td>
                <td class="item_input2">
                    <!--隐藏元素-->
                    <div style="padding:5px">
                      
                        <a href="javascript:void(0)" class="easyui-linkbutton" id="addFromSubmit"> &nbsp  &nbsp &nbsp &nbsp &nbsp 新增 &nbsp  &nbsp &nbsp &nbsp &nbsp </a>

                    </div>

                </td>
            </tr>

        </table>
    }


</div>
<div id="tt">

    <a href="@Url.Action("Index", "MachineModule")" class="icon-back" title="返回列表"></a>
</div>


<style>
    .panel-tool {
        right: initial;
        margin-left: 100px;
    }

    .imgWrap {
        word-wrap: break-word;
        word-break: normal;
        vertical-align: bottom;
        /*margin-top:20px;*/
    }

    .uploader .placeholder {
        padding-top: 0px;
    }

    .queueList {
        width: 800px;
    }

    .uploader .queueList.filled {
        padding: 0px;
    }
</style>



@Html.IncludeScript("~/Content/JS/MachineModule/edit.js")
@Html.IncludeCSS("~/Content/plug-in/ztree/css/zTreeStyle/zTreeStyle.css")

@Html.IncludeScript("~/Content/plug-in/ztree/js/jquery.ztree.core-3.5.js")
@Html.IncludeScript("~/Content/plug-in/ztree/js/jquery.ztree.excheck-3.5.js")
<script>
    @*var sourceFileListObj = eval(@Html.Raw( Json.Encode(@Model.SourceFileList)));*@
    //var sourceFileListObj = null;
    //var upLoader = $("#uploader").WebUploaderMVC({ Controllers: "/MachineModule/", action: "/UpLoadProcess", sourceFileList: sourceFileListObj });
    ///调用文件上传
    var upLoader = $("#uploader").WebUploaderMVC({ Controllers: "/MachineModule/", action: "/UpLoadProcess"});

    function GetFromJsonData() {
        var json = {
            "Name": $("#Name").val(),
            "LinkUrl": $("#LinkUrl").val(),
            "DeptId": $("#DeptId").val(),
            "Sort": $("#Sort").val(),
            "ModuleKey": $("#ModuleKey").val(),
            "Icon": $("#Icon").val(),
            "ID": $("#ID").val(),
            "SourceFileList": upLoader.getSourceFileList()

        };
        return json;
    }


    $("#addFromSubmit").click(function () {

        if (!$("#AddForm").form('validate')) {
            return false;
        }
        var objJson = GetFromJsonData();
        if (objJson.SourceFileList == null || objJson.SourceFileList.length < 1 || upLoader.getfileCount() < 1) {
            alert("请先选择并上传至少一文件");
            return false;
        }

        if (objJson.SourceFileList.length != upLoader.getfileCount()) {
            alert("还有文件未上传");
            return false;
        }
        $.ajax({
            type: "POST",
            url: "/MachineModule/PostAdd",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(objJson),
            dataType: "json",
            success: function (data) {
                if (data.Status == true) {
                    alert("添加成功");
                    $('#AddForm').form('clear');
                    location.reload();

                } else {
                    alert(data.Info);
                }
            },
            error: function (data) {
                alert("添加失败");
            }
        });
    });

</script>





<style>
    .imgWrap {
        word-wrap: break-word;
        word-break: normal;
        vertical-align: bottom;
        /*margin-top:20px;*/
    }
</style>
@*显示行政区域tree*@
<script type="text/javascript">
    var zNodes =@(Html.Raw(ViewData["Department_List"].ToString()));
  
    $("#CoverCommunity").TreeMvc({Department_List:zNodes});
</script>

LoveBank.Web.Admin/Views/MachineModule/Edit.cshtml
@using LoveBank.MVC
@model LoveBank.Web.Admin.Models.MachineModuleShowManageModel
@Html.IncludeCSS("~/Content/plug-in/webuploader/webuploader.css")
@Html.IncludeScript("~/Content/plug-in/webuploader/webuploader.js")
@Html.IncludeCSS("~/Content/Css/demo.css")
@Html.IncludeCSS("~/Content/plug-in/webuploader/demo.css")

<div id="p" class="easyui-panel" title="新增一体机授权" data-options="tools:'#tt'">
    @using (Html.BeginForm("PostEdit", "MachineModule", FormMethod.Post, new { name = "AddForm", id = "AddForm" }))
    {
        <table class="form">


            <tr>
                <td class="item_title">
                    模块名称:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " id="Name" name="Name"
                           value="@Model.Name" data-options="required:true,validType:'length[2,20]'" /> (必须填)

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    连接Url:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " name="LinkUrl" id="LinkUrl"
                           value="@Model.LinkUrl" data-options="required:true,validType:'length[3,500]'" /> (必填)

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    顺序:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " name="Sort" id="Sort"
                           value="@Model.Sort"  data-options="required:true,validType:'length[1,5]'" /> (必填)

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    自定义唯一标识:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " name="ModuleKey" id="ModuleKey"
                           value="@Model.ModuleKey"   data-options="required:true,validType:'length[1,50]'" /> (必填)

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    压下图标:
                </td>
                <td class="item_input">
                    <input class="easyui-validatebox" type="text" style="height:25px; width:260px;   " name="Icon" id="Icon"
                           value="@Model.Icon" data-options="required:false,validType:'length[1,200]'" />
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    显示ICON:
                </td>
                <td class="item_input">
                    <div id="uploader" class="wu-example uploader" style="width:700px;margin-left:0px;">
                        <div class="queueList" style=" margin:0px; ">
                            <div id="dndArea" class="placeholder">
                                <div id="filePicker"></div>
                                <p>或将文件拖到这里,多可选5个文件（只能上传视频或者图片）</p>
                            </div>
                        </div>
                        <div class="statusBar" style="display:none;">
                            <div class="progress">
                                <span class="text">0%</span>
                                <span class="percentage"></span>
                            </div><div class="info"></div>
                            <div class="btns">
                                <div id="filePicker2" class="filePicker2"></div><div class="uploadBtn">开始上传</div>
                            </div>
                        </div>
                    </div>

                </td>
            </tr>
            <tr>
                <td class="item_title">
                    模块覆盖区域:
                </td>
                <td class="item_input">
                    <input type="hidden" name="DeptId" id="DeptId" value="@Model.DeptId" />
                    <input type="text" class="easyui-validatebox" value="@Model.Department.Name" data-options="prompt:'必填.',required:true" style="height:25px; width:260px;   " id="CoverCommunity" name="CoverCommunity" onclick="showMenu(); return false;" />(必填)
                    <div id="menuContent" class="menuContent" style="display:none; z-index:10000;width:260px;  position: absolute;">
                        <ul id="ztree" class="ztree" style="margin-top:0; background-color:#edf3f7;  overflow:scroll; border:solid 1px #ccc;"></ul>
                    </div>

                </td>
            </tr>
     
            <tr>
                <td class="item_title"></td>
                <td class="item_input2">
                    <!--隐藏元素-->
                    <div style="padding:5px">
                        <input type="hidden" id="ID" name="ID" value="@Model.ID" />
                        <a href="javascript:void(0)" class="easyui-linkbutton" id="addFromSubmit"> &nbsp  &nbsp &nbsp &nbsp &nbsp 修改 &nbsp  &nbsp &nbsp &nbsp &nbsp </a>

                    </div>

                </td>
            </tr>

        </table>
    }


</div>
<div id="tt">

    <a href="@Url.Action("Index", "MachineModule")" class="icon-back" title="返回列表"></a>
</div>

<style>
    .panel-tool {
        right: initial;
        margin-left: 100px;
    }
</style>


@Html.IncludeScript("~/Content/JS/MachineModule/edit.js")
@Html.IncludeCSS("~/Content/plug-in/ztree/css/zTreeStyle/zTreeStyle.css")

@Html.IncludeScript("~/Content/plug-in/ztree/js/jquery.ztree.core-3.5.js")
@Html.IncludeScript("~/Content/plug-in/ztree/js/jquery.ztree.excheck-3.5.js")
<script>
    var sourceFileListObj = eval(@Html.Raw( Json.Encode(@Model.SourceFileList)));
    var upLoader = $("#uploader").WebUploaderMVC({ Controllers: "/MachineModule/", action: "/UpLoadProcess", sourceFileList: sourceFileListObj });

    function GetFromJsonData() {
        var json = {
            "Name": $("#Name").val(),
            "LinkUrl": $("#LinkUrl").val(),
            "DeptId": $("#DeptId").val(),
            "Sort": $("#Sort").val(),
            "ModuleKey": $("#ModuleKey").val(),
            "Icon": $("#Icon").val(),
            "ID": $("#ID").val(),
            "SourceFileList": upLoader.getSourceFileList()

        };
        return json;
    }


    $("#addFromSubmit").click(function () {

        if (!$("#AddForm").form('validate')) {
            return false;
        }
        var objJson = GetFromJsonData();
        if (objJson.SourceFileList == null || objJson.SourceFileList.length < 1 || upLoader.getfileCount() < 1) {
            alert("请先选择并上传至少一文件");
            return false;
        }

        if (objJson.SourceFileList.length != upLoader.getfileCount()) {
            alert("还有文件未上传");
            return false;
        }
        $.ajax({
            type: "POST",
            url: "/MachineModule/PostEdit",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(objJson),
            dataType: "json",
            success: function (data) {
                if (data.Status == true) {
                    alert("添加成功");
                    $('#AddForm').form('clear');
                    location.reload();

                } else {
                    alert(data.Info);
                }
            },
            error: function (data) {
                alert("添加失败");
            }
        });
    });

</script>





<style>
    .imgWrap {
        word-wrap: break-word;
        word-break: normal;
        vertical-align: bottom;
        /*margin-top:20px;*/
    }
</style>

<script type="text/javascript">


    var setting = {
        view: {
            dblClickExpand: false,
            showLine: true,
            selectedMulti: false

        },
        check: {
            enable: true ,
            chkStyle: "radio",
            radioType: "all"
        },
        data: {
            simpleData: {
                enable: true,
                idKey: "Id",
                pIdKey: "PId",
                rootPId: ""
            },
            key: {
                name: "Name"
            }

        },
        callback: {
            beforeCheck: beforeCheck,
            onCheck: onCheck
        }
    };

    var zNodes =@(Html.Raw(ViewData["Department_List"].ToString()));


    function beforeCheck(treeId, treeNode) {

    }
    function onCheck(e, treeId, treeNode) {
        $("#DeptId").val(treeNode.Id);
        $("#CoverCommunity").val(treeNode.Name);
    }

    function showMenu() {
        $("#menuContent").slideDown("fast");
        $("body").bind("mousedown", onBodyDown);
    }
    function hideMenu() {
        $("#menuContent").fadeOut("fast");
        $("body").unbind("mousedown", onBodyDown);
    }
    function onBodyDown(event) {
        if (!(event.target.id == "menuBtn" || event.target.id == "menuContent" || $(event.target).parents("#menuContent").length>0)) {
            hideMenu();
        }
    }


    $(document).ready(function () {
        $.fn.zTree.init($("#ztree"), setting, zNodes);
    });

</script>

LoveBank.Web.Admin/Views/MachineModule/Index.cshtml
@model  LoveBank.Web.Admin.Models.MachineModuleShowManageModel
@using MvcContrib.UI.Pager;
@using LoveBank.Common
@using LoveBank.MVC
@using LoveBank.MVC.UI
@using MvcContrib.UI.Grid

@section HeadSection {
    <script type="text/javascript">
   
        function del(id) {

            var url = '@Url.Action("Delete")' + '?id=' + id;
            deleteMethod(id, "Delete");
        
        }
        function submitForm() {
            // var url = "/SocSer/PostNoTakeIn" + '?detailId=' + id + "&state=" + state + "&msg=" + msg;
            $('#indexFrom').submit();
        }
    </script>

}


@*<div id="button_row">

    <a class="easyui-linkbutton" data-options="iconCls:'icon-add'" href="@Url.Action("Add")">新增板块</a>
</div>*@
<form id="indexFrom">

    <div style="float: left;  text-align: center;">
        <span>
            <a class="easyui-linkbutton" data-options="iconCls:'icon-add'" href="@Url.Action("Add")">新增板块</a>
        </span>
        <span style="margin-left:30px;">
            <span>

                <input type="hidden" name="DeptId" id="DeptId" value="@Model.DeptId" />
                所属区域 <input type="text" class="easyui-validatebox" value="@Model.DeptIdName" data-options="prompt:'必填.',required:true" style="height:25px; width:260px;   " id="CoverCommunity" name="DeptIdName" onclick="showMenu(); return false;" />(必填)
                <div id="menuContent" class="menuContent" style="display:none; margin-left:190px; z-index:10000;width:260px;  position: absolute;">
                    <ul id="ztree" class="ztree" style="margin-top:0; background-color:#edf3f7;  overflow:scroll; border:solid 1px #ccc;"></ul>
                </div>

            </span>

            <a href="javascript:void(0)" class="easyui-linkbutton" onclick="submitForm()">查询</a>
        </span>
    </div>
</form>
<div class="grid_box">

    @Html.Grid(Model.MachineModuleModelList).Columns(column =>
    {
        //column.CheckBox(x => x.Id);
        column.For(x => x.ID).Named("ID");
        column.For(x => x.Name?? "").Named("名称");
        column.For(x => x.LinkUrl ?? "").Named("连接地址");
        column.For(x => x.Sort).Named("显示顺序");
        column.For(x => x.ModuleKey ?? "").Named("模块自定义标识");
        column.For(x => x.AddTime.ToString("yyyy-MM-dd")).Named("注册时间");
        column.For(x => x.Department.Name).Named("显示地区");
        //column.For(x => (x.Department ?? new LoveBank.Core.Domain.Department()).Name ?? "").Named("所属区域");
        column.For(x => x.State).Named("状态");

        column.Buttons(btns => btns.Add(x => Html.ActionLink("编辑", "Edit", new { id = x.ID }))
            .Add(x => Html.ScriptLink("删除", "del({0})", x.ID))

            );
    }).Complex(ViewData)

</div>

@Html.Pager(Model.MachineModuleModelList)

@Html.IncludeScript("~/Content/JS/MachineModule/edit.js")
@Html.IncludeCSS("~/Content/plug-in/ztree/css/zTreeStyle/zTreeStyle.css")

@Html.IncludeScript("~/Content/plug-in/ztree/js/jquery.ztree.core-3.5.js")
@Html.IncludeScript("~/Content/plug-in/ztree/js/jquery.ztree.excheck-3.5.js")
<script type="text/javascript">
    var zNodes =@(Html.Raw(ViewData["Department_List"].ToString()));

    $("#CoverCommunity").TreeMvc({Department_List:zNodes});


    $("#CoverCommunity").change(function(){
        if (!$(this).val()||$(this).val()=="") {
            $("#DeptId").val("");
        }
    });
</script>