LoveBank.Web/Controllers/ConvenienceServicesController.cs
using System.Linq;
using System;
using System.Web.Mvc;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;
using LoveBank.Common;
using LoveBank.Core.Domain;
using LoveBank.Services.AdminModule;
using LoveBank.Common.Data;
using LoveBank.MVC.Security;
using LoveBank.Core.MSData;
using LoveBank.Core.Domain.Enums;
using System.IO;
using System.Web;
using LoveBank.Services;
using LoveBank.Core.SerializerHelp;
using System.Collections.Generic;
using System.Threading.Tasks;
using LoveBank.Web.Models;

namespace LoveBank.Web.Controllers
{
    public class ConvenienceServicesController : BaseController
    {

        public ActionResult Index(ConvenienceServicesType type, int page = 1, int pageSize = 8)
        {
            ConvenienceServicesModel model = new ConvenienceServicesModel();
            model.Type = type;
            //获取最近的列表
            //var list = Task.Factory.StartNew<List<ConvenienceServicesModel>>(() =>
            //{
            //    return GetListConvenienceServices(type, page, pageSize);
            //});

            ////获取最新的一篇文章
            //var NewConvenienceServices = Task.Factory.StartNew<ConvenienceServicesModel>(() =>
            //{
            //    return GetNewConvenienceServices(type);
            //});

            //Task.WaitAll(list, NewConvenienceServices);

            //model = NewConvenienceServices.Result;
            model.ConvenienceServicesModelList = GetListConvenienceServices(type, page, pageSize);

            return View(model);
        }

        //获取详情
        public ActionResult Detail(int Id)
        {
            using (LoveBankDBContext db = new LoveBankDBContext())
            {
                var tws = db.T_ConvenienceServices;
                var detailModel = (from w in tws
                                   where w.ID == Id
                                   select new ConvenienceServicesModel
                                   {
                                       AddTime = w.AddTime,
                                       Title = w.Title,
                                       DeptId = w.DeptId,
                                       Content = w.Content
                                   }).FirstOrDefault();
                return View(detailModel);

            }
        }

        //获取最近的列表
        private IPagedList<ConvenienceServicesModel> GetListConvenienceServices(ConvenienceServicesType type, int page = 1, int pageSize = 8)
        {
            using (LoveBankDBContext db = new LoveBankDBContext())
            {
                var tws = db.T_ConvenienceServices;
                var list2 = from w in tws
                            select new ConvenienceServicesModel
                            {
                                AddTime = w.AddTime,
                                Title = w.Title,
                                DeptId = w.DeptId,
                                Sort = w.Sort,
                                Type = w.Type
                            };
                if (type != ConvenienceServicesType.所有便民服务)
                {
                    list2 = list2.Where(x => x.Type == type);
                }

                return list2.Where(x => x.DeptId == BaseWebSiteConifg.DeptId).OrderByDescending(x => x.Sort).ToPagedList(page-1, pageSize);

            }
        }

        //获取最新的爱心基金
        private ConvenienceServicesModel GetNewConvenienceServices(ConvenienceServicesType type)
        {
            using (LoveBankDBContext db = new LoveBankDBContext())
            {
                var tws = db.T_ConvenienceServices;
                var list2 = from w in tws
                            select new ConvenienceServicesModel
                            {
                                AddTime = w.AddTime,
                                Title = w.Title,
                                DeptId = w.DeptId,
                                Sort = w.Sort,
                                Type = w.Type
                            };
                return list2.Where(x => x.DeptId == BaseWebSiteConifg.DeptId && x.Type == type).OrderByDescending(x => x.Sort).FirstOrDefault();
            }
        }
	}
}

LoveBank.Web/Views/ConvenienceServices/Index.cshtml


<link rel="stylesheet" href="@Url.Content("~/Content/Web/css/fundpublic.css")">
<link rel="stylesheet" href="@Url.Content("~/Content/Web/css/lovefund.css")">
@model LoveBank.Web.Models.ConvenienceServicesModel
@using MvcContrib.UI.Pager;
@using LoveBank.Common
@using LoveBank.MVC
@using LoveBank.MVC.UI
@using MvcContrib.UI.Grid
<style type="text/css">
    #bgimg {
        height: 7px;
        background-color: #00AF62;
    }

    #footer {
        border-top: 1px solid #ccc;
    }

    #main .x_sev_info .ull {
        padding-top: 10px;
    }

        #main .x_sev_info .ull li {
            line-height: 20px;
            text-indent: 10px;
        }

        #main .x_sev_info .ull .bm-title {
            font-size: 24px;
            color: #00AF62;
            text-indent: 0;
            padding-top: 20px;
            cursor: default;
        }

            #main .x_sev_info .ull .bm-title img {
                vertical-align: -1px;
                margin-right: 4%;
            }
</style>

<div id="bgimg" class="x_ind_bgimg">
</div>
<div class="bigbg">
    <div id="main">
        <div class="x_sev_info">
            <div class="fl dis-ib flbox">
                <div class="fll">
                    <a href="@Url.Action("index", "ConvenienceServices", new { type = 0 })" style="color: #fff;">
                        <img src="@Url.Content("~/Content/Web/img/house.png")" alt="">
                        &nbsp;便民服务
                        <img src="@Url.Content("~/Content/Web/img/sj.png")" class="sj" alt="">
                    </a>
              </div>
                <ul class="ull">
                    <li class="bm-title"><img src="@Url.Content("~/Content/Web/img/house_1.png")" alt="">行政便民服务资源</li>
                    <li>
                        <a href="@Url.Action("index", "ConvenienceServices", new { type = 1 })" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/grov_01.png")" alt="" />社区所办事项所需资料
                        </a>
                        <span class="fr l_grov_active"></span>
                    </li>

                    <li>
                        <a href="@Url.Action("index", "ConvenienceServices", new { type = 2 })" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/grov_02.png")" alt="">最新福利，救助等整策更新
                        </a>
                        <span class="fr"></span>
                    </li>

                    @*<li>
                        <a href="###" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/grov_03.png")" alt="">便民网站链接
                        </a>
                        <span class="fr"></span>
                    </li>*@

                    <li class="bm-title"><img src="@Url.Content("~/Content/Web/img/house_2.png")" alt="">社区便民商业服务网络</li>
                    <li>
                        <a href="@Url.Action("index", "ConvenienceServices", new { type = 3 })" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/house_21.png")" alt="" />社区商业资源介绍
                        </a>
                        <span class="fr"></span>
                    </li>

                    <li>
                        <a href="@Url.Action("index", "ConvenienceServices", new { type = 4 })" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/house_22.png")" alt="">爱心企业活动预告
                        </a>
                        <span class="fr"></span>
                    </li>


                    @*<li class="bm-title"><img src="@Url.Content("~/Content/Web/img/house_3.png")" alt="">服务中心介绍</li>
                    <li>
                        <a href="###" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/house_31.png")" alt="" />社区商业资源介绍
                        </a>
                        <span class="fr"></span>
                    </li>

                    <li>
                        <a href="###" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/house_32.png")" alt="">爱心企业活动预告
                        </a>
                        <span class="fr"></span>
                    </li>

                    <li>
                        <a href="@Url.Action("index", "ConvenienceServices", new { type = 4 })" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/house_33.png")" alt="">爱心企业活动预告
                        </a>
                        <span class="fr"></span>
                    </li>*@

                ></ul>
            </div>

            <div class="fl dis-ib l_serve_model">
                <div class="flr">
                    <img src="@Url.Content("~/Content/Web/img/love_fund_title_r.png")" alt="">

                    @Model.Type.ToLocalizable()
                    <img src="@Url.Content("~/Content/Web/img/sj.png")" class="sj" alt="">
                </div>
                <div class="l_lovefund_intro">

                    <ul class="ulr">
                        @foreach (var item in Model.ConvenienceServicesModelList)
                        {
                            <li class="l_lovefund_list">

                                <a class="fl l_lovefund_introl" href="severCenterdetails.html">&gt;&nbsp;&nbsp;@item.Title</a>
                                <span class="time fr">@item.AddTime.ToString("yyyy-MM-dd")</span>
                            </li>
                        }



                    </ul>


                    <p class="l_addheight"></p>



                    @Html.WebPager(Model.ConvenienceServicesModelList)


                </div>
            </div>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        var arrcolors = ["", "#fd4565", "#45a5f5", "", "#1395F7", "#FF7F95", "", "#7687F1", "#1395F7", "#FF8243"];
        var commcolor = "#cccccc";
        var listIndex =@((int)Model.Type);
        $(".ull li").eq(1).find("a").css("color", arrcolors[1]).parent().find("span").css("backgroundColor", arrcolors[1]);
        $(".ull").find("li").click(function () {
            $(this).find("a").css("color", arrcolors[$(this).index()]);
            $(this).find("span").css("backgroundColor", arrcolors[$(this).index()]);
            $(this).siblings().find("span").css("backgroundColor", commcolor);
            $(this).siblings().find("a").css("color", "#666");
           
        })

        if (listIndex >= 0) {
         
            if (listIndex>=3) {
                $(".ull").find("li:eq(" + (listIndex+1) + ")").click();
          
            }else {
                $(".ull").find("li:eq(" + (listIndex) + ")").click();
            }
          
        }

    })
</script>