LoveBank.Web/Controllers/CServiceCenterInfoController.cs
using System.Linq;
using System;
using System.Web.Mvc;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;
using LoveBank.Common;
using LoveBank.Core.Domain;
using LoveBank.Services.AdminModule;
using LoveBank.Common.Data;
using LoveBank.MVC.Security;
using LoveBank.Core.MSData;
using LoveBank.Core.Domain.Enums;
using System.IO;
using System.Web;
using LoveBank.Services;
using LoveBank.Core.SerializerHelp;
using System.Collections.Generic;
using System.Threading.Tasks;
using LoveBank.Web.Models;


namespace LoveBank.Web.Controllers
{
    public class CServiceCenterInfoController : BaseController
    {
        public ActionResult Index(CServiceCenterInfoType type, int page = 1, int pageSize = 8)
        {
            CServiceCenterInfoModel model = new CServiceCenterInfoModel();
            model.Type = type;
       
            model.CServiceCenterInfoPageList = GetListCServiceCenterInfo(type, page, pageSize);

            return View(model);

        }

        //获取详情
        public ActionResult Detail(int Id)
        {
            using (LoveBankDBContext db = new LoveBankDBContext())
            {
                var tws = db.T_CServiceCenterInfo;
                var detailModel = (from w in tws
                                   where w.ID == Id
                                   select new CServiceCenterInfoModel
                                   {
                                       AddTime = w.AddTime,
                                       Title = w.Title,
                                       DeptId = w.DeptId,
                                       Content = w.Content
                                   }).FirstOrDefault();
                return View(detailModel);

            }
        }

        //获取最近的列表
        private IPagedList<CServiceCenterInfoModel> GetListCServiceCenterInfo(CServiceCenterInfoType type, int page = 1, int pageSize = 8)
        {
            using (LoveBankDBContext db = new LoveBankDBContext())
            {
                var tws = db.T_CServiceCenterInfo;
                var list2 = from w in tws
                            select new CServiceCenterInfoModel
                            {
                                AddTime = w.AddTime,
                                Title = w.Title,
                                DeptId = w.DeptId,
                                Sort = w.Sort,
                                Type = w.Type
                            };

                if (type != CServiceCenterInfoType.服务中心)
                {
                    list2 = list2.Where(x => x.Type == type);
                }

                return list2.Where(x => x.DeptId == BaseWebSiteConifg.DeptId).OrderByDescending(x => x.Sort).ToPagedList(page-1, pageSize);

            }
        }

        //获取最新的爱心基金
        private CServiceCenterInfoModel GetNewCServiceCenterInfo(CServiceCenterInfoType type)
        {
            using (LoveBankDBContext db = new LoveBankDBContext())
            {
                var tws = db.T_CServiceCenterInfo;
                var list2 = from w in tws
                            select new CServiceCenterInfoModel
                            {
                                AddTime = w.AddTime,
                                Title = w.Title,
                                DeptId = w.DeptId,
                                Sort = w.Sort,
                                Type = w.Type
                            };
                return list2.Where(x => x.DeptId == BaseWebSiteConifg.DeptId && x.Type == type).OrderByDescending(x => x.Sort).FirstOrDefault();
            }
        }
	}
}

LoveBank.Web/Views/CServiceCenterInfo/Index.cshtml
<link rel="stylesheet" href="@Url.Content("~/Content/Web/css/fundpublic.css")">
<link rel="stylesheet" href="@Url.Content("~/Content/Web/css/lovefund.css")">
@model LoveBank.Web.Models.CServiceCenterInfoModel
@using MvcContrib.UI.Pager;
@using LoveBank.Common
@using LoveBank.MVC
@using LoveBank.MVC.UI
@using MvcContrib.UI.Grid



<div id="bgimg" class="x_ind_bgimg">
</div>
<div class="bigbg">
    <div id="main">
        <div class="x_sev_info">
            <div class="fl dis-ib flbox">
                <div class="fll">
                    <a href="@Url.Action("index", "CServiceCenterInfo", new { type = 0 })" style="color: #fff;">
                        <img src="@Url.Content("~/Content/Web/img/shequ_l.png")" alt="">
                        &nbsp;服务中心介绍
                        <img src="@Url.Content("~/Content/Web/img/sj.png")" class="sj" alt="">
                    </a>
               </div>

                <ul class="ull">
                    <li>
                        <a href="@Url.Action("index", "CServiceCenterInfo", new { type = 1 })" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/shequ_01.png")" alt="">简介
                        </a>
                        <span class="fr l_shequ_active"></span>
                    </li>

                    <li>
                        <a href="@Url.Action("index", "CServiceCenterInfo", new { type = 2 })" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/shequ_02.png")" alt="">服务项目介绍
                        </a>
                        <span class="fr"></span>
                    </li>

                    <li>
                        <a href="@Url.Action("index", "CServiceCenterInfo", new { type = 3 })" class="fl">

                            <img src="@Url.Content("~/Content/Web/img/shequ_03.png")" alt="">社工风采等
                        </a>
                        <span class="fr"></span>
                    </li>



                </ul>
            </div>

            <div class="fl dis-ib l_serve_model">
                <div class="flr">
                    <img src="@Url.Content("~/Content/Web/img/shequ_r.png")" alt="">
                    @Model.Type.ToLocalizable()
                    <img src="@Url.Content("~/Content/Web/mg/sj.png")" class="sj" alt="">
                </div>
                <div class="l_lovefund_intro">

                    <ul class="ulr">
                     

                        @foreach (var item in Model.CServiceCenterInfoPageList)
                        {
                            <li class="l_lovefund_list">

                                <a class="fl l_lovefund_introl" href="severCenterdetails.html">&gt;&nbsp;&nbsp;@item.Title</a>
                                <span class="time fr">@item.AddTime.ToString("yyyy-MM-dd")</span>
                            </li>
                        }





                    </ul>
                    <p class="l_addheight"></p>


                    @Html.WebPager(Model.CServiceCenterInfoPageList)
                </div>
            </div>


        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        var arrcolors = ["#7687f1", "#1093f6", "#ff8243"];

        var commcolor = "#cccccc";
        var listIndex =@((int)Model.Type) -1;

        $(".ull").find("li").click(function () {
            $(this).find("a").css("color", arrcolors[$(this).index()]);
            $(this).find("span").css("backgroundColor", arrcolors[$(this).index()]);
            $(this).siblings().find("span").css("backgroundColor", commcolor);
            $(this).siblings().find("a").css("color", "#666");
        
        })
        if (listIndex>=0) {
            $(".ull").find("li:eq(" + listIndex + ")").click();
        }

    })
</script>